Adding new util function to generate JWE
fewlinesco/connect-js pull request #36
Opened 2021-04-26 11:23 UTC by Oluane

2021-04-26 11:23 UTC, Fenntasy commented
Task linked: [CU-gf90j5 [connect-client] - generate JWE - connect-client](https://app.clickup.com/t/gf90j5)

2021-04-26 11:55 UTC, Fuzznimp approved these changes

2021-04-26 12:23 UTC, Meyclem submitted a review, later dismissed

2021-04-26 13:12 UTC, Meyclem requested changes
Do we want this function to take a payload or a jws?
Or do we want it to signed a payload to make it a jws **inside** the function?
I ask because I find it a bit weird to use different types like this for the "main" parameter

2021-04-26 13:12 UTC, Meyclem commented on client/tests/index.test.ts
> +    test.only("it should correctly decrypt a JWE based on non-signed JWT", async () => {
```suggestion
    test("it should correctly decrypt a JWE based on non-signed JWT", async () => {
```

2021-04-26 13:40 UTC, Oluane commented
@Meyclem I see your point, I asked myself the same questions, but here are the reasons I did it that way: 
I wanted to add support for non-signed JWT because some months ago, when I worked on `decryptJWE`, I used tokens sent by Connect at this moment to do local tests, and found that they weren't sending JWEs based on a JWS, but on a non-signed JWT. When decrypting them, I didn't had a string (like `eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJhdWQiOlsib2F1dGgyIl0sImV4cCI6MTYxOTQ0MzYyMzIzNSwiaXNzIjoiaHR0cH...`) in the end, but an object-like payload. Since Connect can do the both, we decided to support the both for `decryptJWE` too. 
The thing is, it isn't really clear for me at this moment what a non-signed JWT should look like, and I assumed that what Connect did was the way to go, meaning: a non-signed JWT is a clear payload (a simple object). That's why the main argument of `generateJWE` is either a clear payload object, either a string token.

2021-04-26 13:46 UTC, Meyclem commented
Ok
What I suggested was more something like this:
```typescript
async function generateJWE(
  JWTPayload,
  publicKey: string,
  secretKey?: string
): Promise<string> {
  const josePublicKeyForEncryption = await jose.JWK.asKey(publicKey, "pem");

  let token;

  if (secretKey) {
    token = /** If there's a secretKey, make it a JWS */
  } else {
    token = JSON.stringify(JWTPayloadOrJWS);
  }

  return await jose.JWE.createEncrypt(
    { format: "compact" },
    josePublicKeyForEncryption,
  )
    .update(Buffer.from(JWTOrJWS))
    .final();
}
```
So in the end, we always give it a payload and only if there's a secret key to sign with, we make it a JWS.

The JWT is pretty much the same thing as the JWS, with less parts (because the signed part is not there).
e.g:
```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
```
> Only 3 parts, so it is not sign

2021-04-26 13:56 UTC, Fuzznimp commented
And the JWT you gave is a HS256 signed JWT :).

2021-04-26 16:05 UTC, Fuzznimp submitted a review, later dismissed

2021-04-27 07:19 UTC, Meyclem approved these changes

2021-04-27 07:49 UTC, Fuzznimp approved these changes

2021-04-27 08:14 UTC, merged